tasks:
  ourbits:  
    rss:
      url: https://*******
      other_fields:
        - link
    limit_new: 2
    content_size:
      min: 12000
      max: 150000
      # strict: no
    nexusphp:
      cookie: ''
      hr: no
      seeders:
        min: 1
        max: 3
      leechers:
        min: 20
        # max_complete: 0.2
    download: C:/flexget_amt/flexget/torrents/