my_task:
  client: qbittorrent
  host: http://127.0.0.1:8080
  username: ***
  password: ****
  strategies:
    strategy1:
      all_categories: true
      free_space:
        min: 100
        # path: D:/*
        action: remove-old-seeds
  delete_data: true
